DROP DATABASE IF EXISTS beatrice;
CREATE DATABASE beatrice;
USE beatrice;

CREATE TABLE user (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	user_id VARCHAR(18) NOT NULL UNIQUE
);

CREATE TABLE playlist (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	count INTEGER NOT NULL,
	total_time INTEGER NOT NULL,
	author INTEGER NOT NULL,

	FOREIGN KEY (author) REFERENCES user(id)
);

CREATE TABLE collaboration (
	collaborator INTEGER NOT NULL,
	playlist_id INTEGER NOT NULL,

	primary key (collaborator, playlist_id),
	FOREIGN KEY (collaborator) REFERENCES user(id) ON DELETE CASCADE,
	FOREIGN KEY (playlist_id) REFERENCES playlist(id) ON DELETE CASCADE
);

CREATE TABLE song (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	name VARCHAR(50) NOT NULL,
	url VARCHAR(255) NOT NULL,
	length INTEGER NOT NULL,
	playlist_id INTEGER NOT NULL,

	FOREIGN KEY (playlist_id) REFERENCES playlist(id) ON DELETE CASCADE
);

CREATE TABLE birthday (
	id INTEGER PRIMARY KEY AUTO_INCREMENT,
	`date` DATE NOT NULL,
	flag INTEGER NOT NULL DEFAULT 0,
	user_id INTEGER NOT NULL,

	FOREIGN KEY (user_id) REFERENCES user(id) ON DELETE CASCADE
);